apiVersion: v1
kind: Secret
metadata:
  name: fastapi-dev-secret
  namespace: project-a1
type: Opaque
stringData:
  DB_HOST: "192.168.105.81"
  DB_PORT: "3306"
  DB_NAME: "projecta1"
  DB_USER: "hj-db"
  DB_PASS: "Hani6967!"
  JWT_SECRET: "dev-secret"
