apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend
  namespace: project-a1
spec:
  type: ClusterIP
  selector:
    app: fastapi-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
