apiVersion: v1
kind: Service
metadata:
  name: flutter-frontend
  namespace: project-a1
spec:
  type: ClusterIP
  selector:
    app: flutter-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
