apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-frontend
  namespace: project-a1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flutter-frontend
  template:
    metadata:
      labels:
        app: flutter-frontend
    spec:
      containers:
      - name: flutter
        image: ghcr.io/liamParkDev/project-a1-flutter:latest
        ports:
        - containerPort: 80
