apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-frontend
  namespace: project-a1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flutter-frontend
  template:
    metadata:
      labels:
        app: flutter-frontend
    spec:
      containers:
        - name: flutter
          image: nginx:1.25
          ports:
            - containerPort: 80
