apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-a1-ingress
  namespace: project-a1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: app.local
    http:
      paths:
      # FastAPI
      - path: /api/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fastapi-backend
            port:
              number: 8000

      # Flutter Web
      - path: /(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: flutter-frontend
            port:
              number: 80
