apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-a1-ingress
  namespace: project-a1
spec:
  ingressClassName: nginx
  rules:
  - host: app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flutter-frontend
            port:
              number: 80

  - host: api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fastapi-backend
            port:
              number: 8000
