apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-a1-ingress
  namespace: project-a1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: app.local
      http:
        paths:
          # FastAPI -> /api/
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: fastapi-backend
                port:
                  number: 8000

          # Flutter Web -> root
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: flutter-frontend
                port:
                  number: 80
