name: Build & Push FastAPI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug backend folder
        run: |
          echo "===== backend files in GH Actions ====="
          ls -R ./backend
          echo "===== requirements.txt ====="
          cat ./backend/requirements.txt
          echo "===== main.py ====="
          cat ./backend/main.py

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: liamparkdev
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/liamparkdev/project-a1-backend:latest ./backend
          
      - name: Push Docker image
        run: |
          docker push ghcr.io/liamparkdev/project-a1-backend:latest
