name: Build & Push Flutter Web

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.24.0"

      - name: Pub get
        working-directory: ./frontend
        run: flutter pub get

      - name: Build Flutter web
        working-directory: ./frontend
        run: flutter build web --release

      - name: Debug build output
        run: ls -R ./frontend/build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: liamparkdev
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/liamparkdev/project-a1-frontend:latest ./frontend

      - name: Push Docker image
        run: docker push ghcr.io/liamparkdev/project-a1-frontend:latest
